###
GET http://localhost:8080/carparks
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

###
GET http://localhost:8080/carparks/4
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

###
POST http://localhost:8080/carparks
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
    "name": "Test2",
    "address": "test 50",
    "prices": 30,
    "floors" :
    [
    ]
}
###
POST http://localhost:8080/carparks
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
    "name": "Test2",
    "address": "test 50",
    "prices": 30
}
###
PUT http://localhost:8080/carparks/1051
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
    "name": "Test",
    "address": "Test 58 updated",
    "prices": 99
}
###
DELETE http://localhost:8080/carparks/952
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=
###
POST http://localhost:8080/users
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
    "firstName": "name",
    "lastName": "surname",
    "email": "aa@aa.com",
    "cars":
    [
        {
            "brand": "skoda",
            "model": "fabia",
            "vrp": "znacka55",
            "colour": "cervena",
            "type":
            {
                "name": "voda"
            },
            "owner":
            {
                "id": 3,
                "firstName": "user",
                "lastName": "last",
                "email": "my@email.com"
            }

        }
    ]
}

###
POST http://localhost:8080/users
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
  "firstName": "user3",
  "lastName": "last3",
  "email": "my3@email.com",
  "cars":[
    {
    "brand": "brand",
    "model": "model",
    "vrp": "BA321",
    "colour": "blue",
    "type":
            {
                "name": "voda"
            },
    "owner": {
      "id": 3,
      "firstName": "user",
      "lastName": "last",
      "email": "my@email.com"
      }
    },
    {
    "brand": "brand",
    "model": "model",
    "vrp": "BA322",
    "colour": "blue",
    "type":
            {
                "name": "voda"
            },
    "owner": {
      "id": 3,
      "firstName": "user",
      "lastName": "last",
      "email": "my@email.com"
      }
    }
  ]
}

###
POST http://localhost:8080/users
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
  "firstName": "user3",
  "lastName": "last3",
  "email": "my3@email.com"

}
###
DELETE http://localhost:8080/users/1504
Accept: application/json
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

###
POST http://localhost:8080/cars
Authorization: Basic YWRtaW5AdnNhLnNrOjE=

{
  "brand": "brand",
  "model": "model",
  "vrp": "BA3216to1",
  "colour": "blue",
   "type":
           {
            "name": "plyn"
           },
  "owner": {
    "firstName": "name",
    "lastName": "last",
    "email": "my35o1@email.com"
    }
}

###
DELETE	http://localhost:8080/users/1701
Authorization: Basic YWRtaW5AdnNhLnNrOjEwMDE=